[versions]

[libraries]
annotations = "org.jetbrains:annotations:26.0.2-1"
paper-api = "com.destroystokyo.paper:paper-api:1.13.2-R0.1-SNAPSHOT"
folia-api = "dev.folia:folia-api:1.19.4-R0.1-SNAPSHOT"
velocity-api = "com.velocitypowered:velocity-api:3.0.0-SNAPSHOT"
sponge-api7 = "org.spongepowered:spongeapi:7.4.0"
sponge-api8 = "org.spongepowered:spongeapi:8.2.0"
sponge-api9 = "org.spongepowered:spongeapi:9.0.0"
sponge-api10 = "org.spongepowered:spongeapi:10.0.0"
sponge-api11 = "org.spongepowered:spongeapi:11.0.0"
sponge-api12 = "org.spongepowered:spongeapi:12.0.0"
sponge-api13 = "org.spongepowered:spongeapi:13.0.0"
sponge-api14 = "org.spongepowered:spongeapi:14.0.0"

junit-bom = "org.junit:junit-bom:6.0.1"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]

[plugins]
publisher = "com.vanniktech.maven.publish:0.35.0"
shadow = "com.gradleup.shadow:9.3.0"
